### ISSUE TITLE
Python Test (Fibonacci)

### ISSUE THREAD

**Issue by jeethub26230** [prodevans/LEAP2.0#10]
### Create a program which returns a Fibonacci Series till the given number.

```

Eg :- 
    fib(x) : Gives the Fibonacci till x number.
```.

**Comment by Debasis500** [comment]
```
#fibonacci sequence up to nth term

a=int(input("How many terms:"))
    
n1,n2 = 0,1
count = 0

if a <= 0:
    print("Enter positive number")
elif a == 1:
    print("Fibonacci sequence")
    print(n1)

else:
    print("Fibonacci sequence:")
    while count < a:
        print(n1)
        nth = n1 + n2
        n1 = n2
        n2 = nth
        count += 1
```

**Comment by simranmaharana** [comment]
n=int(input("enter the value of 'n':"))
a = 0
b = 1
s = 0
c = 1
print("fibonacci series: ",f =" ")
while(c <= n) 
   print(s, f=" ")
   c+= 1
   a=b
   b=s
   s=a+b

**Comment by pranjali301** [comment]
> num=int(input("enter the number:"))

c=0
b=1
sum=0
count=0
print("fibonacci:")
while(count<=num):
    print(sum)
    count+=1
    c=b
    b=sum
    sum=c+b

**Comment by pranjali301** [comment]
num=int(input("enter the number:"))
c=0
b=1
sum=0
count=0
print("fibonacci:")
while(count<=num):
    print(sum)
    count+=1
    c=b
    b=sum
    sum=c+b
    ``

**Comment by pranjali301** [comment]
`num=int(input("enter the number:"))
c=0
b=1
sum=0
count=0
print("fibonacci:")
while(count<=num):
    print(sum)
    count+=1
    c=b
    b=sum
    sum=c+b
    `

**Comment by pranjali301** [comment]
>num=int(input("enter the number:"))
c=0
b=1
sum=0
count=0
print("fibonacci:")
while(count<=num):
    print(sum)
    count+=1
    c=b
    b=sum
    sum=c+b
    ``

**Comment by joellui** [comment]
Click the link ---> [My code](https://github.com/joellui/leap-2.0/blob/master/Fibonacci_number.py)

**Comment by pranjali301** [comment]
`num=int(input("enter the number:"))
`c=0`
`b=1`
`sum=0`
`count=0`
`print("fibonacci:")`
`while(count<=num):`
    `print(sum)`
    `count+=1`
    `c=b`
   `` b=sum
    sum=c+b
    `

**Comment by vamsipvk2203** [comment]
# Fibonacci until given number

```
def fibonacci(val):
    a=0
    b=1
    print(a,b,end=' ')
    for i in range(2,val):
        c = a+b
        if c < val:
            print(c,end=' ')
        else:
            break
        a = b
        b = c
        
        
val = int(input('Enter the number: '))
fibonacci(val)
```

**Comment by simranmaharana** [comment]
n=int(input("enter the value of 'n':"))
a = 0
b = 1
s = 0
c = 1
print("fibonacci series: ",end =" ")
while(c<=n) 
   print(s, end=" ")
   c+= 1
   a=b
   b=s
   s=a+b

**Comment by srvk99** [comment]
#Fibonacci Numbers
```
n = int(input("Enter the number: ")) 
def fib(n):  
   if n <= 1:  
       return(n)  
   else:  
       return(fib(n-1) + fib(n-2))   
if (n<0):  
   print("Positive number please!")  
else:   
   for i in range(n):  
       print(fib(i), end=" ") 
```

**Comment by simranmaharana** [comment]
n=int(input("enter the value of 'n':"))
a = 0
b = 1
s = 0
c = 1
print("fibonacci series: ",end = " ")
while(c <= n) 
   print(s, end= " ")
   c+= 1
   a=b
   b=s
   s=a+b

**Comment by bvjhansisaketa** [comment]
```
i=2
n=int(input("enter the number"))
a2=1
a1=0
print(a1,a2,end=' ')
while(i<n):
    a3=a1+a2
    print(a3,end=' ')
    temp=a2
    a1=temp
    a2=a3
    i=i+1
```

**Comment by kautilya2000** [comment]
```
n = int(input("Enter the value of 'n': "))
a = 0
b = 1
sum = 0
count = 1
print("Fibonacci Series: ", end = " ")
while(count <= n):
  print(sum, end = " ")
  count += 1
  a = b
  b = sum
  sum = a + b
```

**Comment by sravan950** [comment]
def fibonacci(n):
    if(n <= 1):
        return n
    else:
        return(fibonacci(n-1) + fibonacci(n-2))
n = int(input("Enter number of terms:"))
print("Fibonacci sequence:")
for i in range(n):
    print fibonacci(i),

**Comment by VijitSai** [comment]
```
n = int(input("No. of terms "))
a=0
b=1
flag = 0
while flag < n:
    print(a)
    c = a + b
    a = b
    b = c
    flag += 1
```

**Comment by aryaman-01** [comment]
```


nterms = int(input("Number of terms? "))

n1 = 0
n2 = 1
count = 0

if nterms <= 0:
   print("Please enter a positive integer")
elif nterms == 1:
   print("Fibonacci sequence upto",nterms,":")
   print(n1)
else:
   print("Your series is :")
   while count < nterms:
       print(n1)
       nth = n1 + n2
       n1 = n2
       n2 = nth
       count += 1
```

**Comment by Anant777** [comment]
`x=int(input("enter the limits))
i,j=0,1
print("fibonacci sequence : ")
while i<x:
print(i)
nth=i+j
i=j
j=nth`

**Comment by sahoo97** [comment]
n= int( input ("how many term : "))
m1=0
m2=1
c=0
if n<=0:
 print("enter posstive integer number")
else
 print("Fibonacci sequence :  ")
       while c<n
               print(m1)
              mth=m1+m2
               m1=m2
              m2=mth
               c=c+1

**Comment by sravan950** [comment]
Number = int(input("\nPlease Enter the Range Number: "))

FirstValue = 0
SecondValue = 1
           
for Num in range(0, Number):
           if(Num <= 1):
                      Next = Num
           else:
                      Next = FirstValue + SecondValue
                      FirstValue = SecondValue
                      SecondValue = Next
           print(Next)

**Comment by DinuDante** [comment]
```
#This is Dinesh Behera
#Fibinacci Logic and Printing
def fibo(n):
    a,b=0,1
    print("Fibonacci Series:")
    while a<n:
        print(a)
        c=a+b
        a=b
        b=c
#Driver Code
n=int(input("Enter upto limit:"))
if n>0:
    fibo(n)
else:
    print("\n Enter a positive number...")
```

**Comment by m-ankeeta** [comment]
I am M Ankeeta
`
n=int(input('enter the length of series:'))
x=0
y=1
while y<n:
    print(x)
    print(y)
    x = y
    y=x+y
`
```

**Comment by megha-biswas01** [comment]
```
def fibonacci():
    n = int(input("How many terms? "))
    n1, n2 = 0, 1
    count = 0
    if n <= 0:
       print("Please enter a positive integer")
       fibonacci()
    elif n == 1:
       print("Fibonacci sequence upto",n,":")
       print(n1)
    else:
       print("Fibonacci sequence:")
       while count < n:
           print(n1)
           nth = n1 + n2
           n1 = n2
           n2 = nth
           count += 1
print("Welcome")
fibonacci()
option=input(print("Do you want to continue:(y/n)"))
if (option == 'y'):
    fibonacci()
else:
    print("Thank You")
```
